on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Este es un Job para decir Hola
    steps:
    - name: Paso saludo
      id: hello
      uses: actions/hello-world-docker-action@v1
      with:
        who-to-greet: 'Angela'
    # Use the output from the `hello` step
    - name: Hora salida
      run: echo "La hora fue ${{ steps.hello.outputs.time }}"